### ISSUE TITLE
Does not install under Node 10

### ISSUE THREAD

**Issue by davesag** [LinusU/node-generate-rsa-keypair#4]
Under Node 10.0.0 in my [jose-simple](https://github.com/davesag/jose-simple) project I use `generate-rsa-keypair` but it fails to install as follows:

    jose-simple (develop) $ npm install

    > generate-rsa-keypair@0.1.1 install /Users/davesag/src/personal/jose-simple/node_modules/generate-rsa-keypair
    > node-gyp rebuild

      CXX(target) Release/obj.target/generate-rsa-keypair/binding.o
    In file included from ../binding.cc:2:
    In file included from ../../nan/nan.h:192:
    ../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
      return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
             ~~~  ^
    In file included from ../binding.cc:2:
    ../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        return node::MakeCallback(
                     ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
    NODE_DEPRECATED("Use MakeCallback(..., async_context)",
    ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                       ^
    In file included from ../binding.cc:2:
    ../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        return node::MakeCallback(
                     ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
    NODE_DEPRECATED("Use MakeCallback(..., async_context)",
    ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                       ^
    In file included from ../binding.cc:2:
    ../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        return node::MakeCallback(
                     ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
    NODE_DEPRECATED("Use MakeCallback(..., async_context)",
    ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                       ^
    In file included from ../binding.cc:2:
    ../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        return scope.Escape(node::MakeCallback(
                                  ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
    NODE_DEPRECATED("Use MakeCallback(..., async_context)",
    ^
    /Users/davesag/.node-gyp/10.0.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
        __attribute__((deprecated(message))) declarator
                       ^
    ../binding.cc:23:9: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
      rsa = RSA_generate_key(bits, exponent, NULL, NULL);
            ^
    /Users/davesag/.node-gyp/10.0.0/include/node/openssl/rsa.h:193:1: note: 'RSA_generate_key' has been explicitly marked deprecated here
    DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
    ^
    /Users/davesag/.node-gyp/10.0.0/include/node/openssl/./archs/darwin64-x86_64-cc/asm/include/openssl/opensslconf.h:148:34: note: expanded from macro 'DEPRECATEDIN_0_9_8'
    # define DEPRECATEDIN_0_9_8(f)   DECLARE_DEPRECATED(f)
                                     ^
    /Users/davesag/.node-gyp/10.0.0/include/node/openssl/./archs/darwin64-x86_64-cc/asm/include/openssl/opensslconf.h:111:53: note: expanded from macro 'DECLARE_DEPRECATED'
    # define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                                        ^
    5 warnings and 1 error generated.
    make: *** [Release/obj.target/generate-rsa-keypair/binding.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/Users/davesag/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
    gyp ERR! System Darwin 17.5.0
    gyp ERR! command "/Users/davesag/.nvm/versions/node/v10.0.0/bin/node" "/Users/davesag/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/davesag/src/personal/jose-simple/node_modules/generate-rsa-keypair
    gyp ERR! node -v v10.0.0
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! generate-rsa-keypair@0.1.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1

It does install fine under Node 9.11.1 however.

**Comment by LinusU** [comment]
Should work with nan 2.10.x, bumped the dependency. Please test v0.1.2 ☺️

**Comment by davesag** [comment]
yes I can confirm that works.  Updating my project now.  Thanks for your quick response.
