### ISSUE TITLE
Can't install on Windows10/Node 10.16.0

### ISSUE THREAD

**Issue by gregid** [LinusU/node-generate-rsa-keypair#7]
It fails with (translated):
```
node-gyp rebuild
...
binding.obj : error LNK2001: unrecognized external symbol RSA_generate_key
...
```

**Comment by rabble** [comment]
I get the same error on OS X with npm version 6.14.4 & node v12.16.1
 

> `npm install --save generate-rsa-keypair                                                                                                                                  > 1960ms  Thu May 21 15:04:25 2020
> 
> generate-rsa-keypair@0.1.2 install /Users/rabble/code/ssb/rss-to-activitypub/node_modules/generate-rsa-keypair
> node-gyp rebuild
> 
>   CXX(target) Release/obj.target/generate-rsa-keypair/binding.o
> ../binding.cc:23:9: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
>   rsa = RSA_generate_key(bits, exponent, NULL, NULL);
>         ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/openssl/rsa.h:234:1: note: > 'RSA_generate_key' has been explicitly marked deprecated here
> DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
> ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/openssl/./archs/darwin64-x86_64-cc/asm/include/openssl/opensslconf.h:173:34: note: expanded from macro 'DEPRECATEDIN_0_9_8'
> # define DEPRECATEDIN_0_9_8(f)   DECLARE_DEPRECATED(f)
>                                  ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/openssl/./archs/darwin64-x86_64-cc/asm/include/openssl/opensslconf.h:124:55: note: expanded from macro 'DECLARE_DEPRECATED'
> #   define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
>                                                       ^
> ../binding.cc:45:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
>   result->Set(Nan::New<String>("private").ToLocalChecked(), Nan::New<String>(raw, rawLength).ToLocalChecked());
>           ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
>   V8_DEPRECATED("Use maybe version",
>   ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
>   declarator __attribute__((deprecated(message)))
>                             ^
> ../binding.cc:64:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
>   result->Set(Nan::New<String>("public").ToLocalChecked(), Nan::New<String>(raw, rawLength).ToLocalChecked());
>           ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
>   V8_DEPRECATED("Use maybe version",
>   ^
> /Users/rabble/Library/Caches/node-gyp/12.16.1/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
>   declarator __attribute__((deprecated(message)))
>                             ^
> ../binding.cc:71:6: error: variable has incomplete type 'void'
> void Initialize(v8::Handle<v8::Object> exports) {
>      ^
> ../binding.cc:71:21: error: no member named 'Handle' in namespace 'v8'
> void Initialize(v8::Handle<v8::Object> exports) {
>                 ~~~~^
> ../binding.cc:71:38: error: expected '(' for function-style cast or type construction
> void Initialize(v8::Handle<v8::Object> exports) {
>                            ~~~~~~~~~~^
> ../binding.cc:71:40: error: use of undeclared identifier 'exports'
> void Initialize(v8::Handle<v8::Object> exports) {
>                                        ^
> ../binding.cc:71:48: error: expected ';' after top level declarator
> void Initialize(v8::Handle<v8::Object> exports) {
>                                                ^
>                                                ;
> 3 warnings and 5 errors generated.
> make: *** [Release/obj.target/generate-rsa-keypair/binding.o] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Users/rabble/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Darwin 19.4.0
> gyp ERR! command "/Users/rabble/.nvm/versions/node/v12.16.1/bin/node" "/Users/rabble/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/rabble/code/ssb/rss-to-activitypub/node_modules/generate-rsa-keypair
> gyp ERR! node -v v12.16.1
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok
> npm WARN bot-node@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! generate-rsa-keypair@0.1.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the generate-rsa-keypair@0.1.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/rabble/.npm/_logs/2020-05-21T22_04_32_617Z-debug.log`
