### ISSUE TITLE
Cannot install on Mac with Node v13.8.0

### ISSUE THREAD

**Issue by forrestwilkins** [LinusU/node-generate-rsa-keypair#8]
```
💥 npm install generate-rsa-keypair

> generate-rsa-keypair@0.1.2 install /Users/user_1/code/node/express-activitypub/node_modules/generate-rsa-keypair
> node-gyp rebuild

  CXX(target) Release/obj.target/generate-rsa-keypair/binding.o
../binding.cc:23:9: warning: 'RSA_generate_key' is deprecated [-Wdeprecated-declarations]
  rsa = RSA_generate_key(bits, exponent, NULL, NULL);
        ^
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/openssl/rsa.h:234:1: note: 'RSA_generate_key' has been explicitly marked deprecated here
DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
^
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/openssl/./archs/darwin64-x86_64-cc/asm/include/openssl/opensslconf.h:173:34: note: expanded from macro 'DEPRECATEDIN_0_9_8'
# define DEPRECATEDIN_0_9_8(f)   DECLARE_DEPRECATED(f)
                                 ^
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/openssl/./archs/darwin64-x86_64-cc/asm/include/openssl/opensslconf.h:124:55: note: expanded from macro 'DECLARE_DEPRECATED'
#   define DECLARE_DEPRECATED(f)    f __attribute__ ((deprecated));
                                                      ^
../binding.cc:45:11: error: no matching member function for call to 'Set'
  result->Set(Nan::New<String>("private").ToLocalChecked(), Nan::New<String>(raw, rawLength).ToLocalChecked());
  ~~~~~~~~^~~
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../binding.cc:64:11: error: no matching member function for call to 'Set'
  result->Set(Nan::New<String>("public").ToLocalChecked(), Nan::New<String>(raw, rawLength).ToLocalChecked());
  ~~~~~~~~^~~
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/user_1/Library/Caches/node-gyp/13.8.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../binding.cc:71:6: error: variable has incomplete type 'void'
void Initialize(v8::Handle<v8::Object> exports) {
     ^
../binding.cc:71:21: error: no member named 'Handle' in namespace 'v8'
void Initialize(v8::Handle<v8::Object> exports) {
                ~~~~^
../binding.cc:71:38: error: expected '(' for function-style cast or type construction
void Initialize(v8::Handle<v8::Object> exports) {
                           ~~~~~~~~~~^
../binding.cc:71:40: error: use of undeclared identifier 'exports'
void Initialize(v8::Handle<v8::Object> exports) {
                                       ^
../binding.cc:71:48: error: expected ';' after top level declarator
void Initialize(v8::Handle<v8::Object> exports) {
                                               ^
                                               ;
1 warning and 7 errors generated.
make: *** [Release/obj.target/generate-rsa-keypair/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user_1/code/node/express-activitypub/node_modules/generate-rsa-keypair
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN bot-node@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! generate-rsa-keypair@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the generate-rsa-keypair@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user_1/.npm/_logs/2020-04-02T00_39_23_914Z-debug.log
```

**Comment by forrestwilkins** [comment]
Running `npm install generate-rsa-keypair` outside of my project directory got it working somehow.
